name: breast-cancer-data-analysis
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: "3.8"
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python scripts/train.py
          
          echo "## Model metrics" > report.md
          cat data/metrics.txt >> report.md
          
          echo "## Data viz" >> report.md
          cml-publish data/feature_importance.png --md >> report.md
          
          cml-send-comment report.md
